In [1]:
import numpy as np

In [2]:
np.random.rand(1)

array([0.65611319])

In [3]:
np.random.rand(4) #linear distribution

array([0.55701404, 0.95732587, 0.0440237 , 0.94196554])

In [4]:
np.random.rand(5,5)

array([[0.79221087, 0.34822164, 0.52617195, 0.15691363, 0.88538271],
       [0.56290523, 0.21204829, 0.57024063, 0.79936902, 0.20584338],
       [0.50889582, 0.68801325, 0.64091311, 0.00145204, 0.15116246],
       [0.55710712, 0.09172927, 0.24508014, 0.25565701, 0.2796238 ],
       [0.98658928, 0.13813923, 0.52526455, 0.20673257, 0.1038329 ]])

In [5]:
np.random.randn(10) #normal distribution

array([ 0.24297149, -0.12930797,  0.34330437,  1.44145191, -0.40838593,
        0.95911215,  1.51599167,  1.46630905,  1.73115663,  0.31636869])

In [9]:
#np.random.normal()

0.22175054134777195

In [10]:
np.random.randint(1,100,10)

array([26, 23, 65, 56, 13, 63, 18, 28, 14, 71])

In [17]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr = np.random.randint(0,50,10)

In [21]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

48

In [25]:
ranarr.min()

10

In [26]:
ranarr.argmax()

1

In [27]:
ranarr.argmin()

6

In [28]:
ranarr.dtype

dtype('int32')