In [1]:
import numpy as np

In [23]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
slice_of_array = arr[0:6] #affects original array if you modify slice_of_array

In [11]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy() #this way it creates a new array different from the last one
arr_copy[:] = 1000
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_2d = np.array([[5,10,15],[20,25,40],[25,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 40],
       [25, 40, 45]])

In [16]:
arr_2d.shape

(3, 3)

In [17]:
arr_2d[1]

array([20, 25, 40])

In [18]:
arr_2d[1,1]

25

In [21]:
arr_2d[1,1:]

array([25, 40])

In [24]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])